import 'package:flutter/material.dart';
import 'package:uuid/uuid.dart';
import 'package:intl/intl.dart';
import 'package:hive/hive.dart';

part 'expense.g.dart'; // This file will be generated by build_runner

const uuid = Uuid();
final formatter = DateFormat.yMd();

@HiveType(typeId: 0)
enum Category {
  @HiveField(0)
  bajajEmi,
  @HiveField(1)
  homeRent,
  @HiveField(2)
  electricityBill,
  @HiveField(3)
  zomat,
  @HiveField(4)
  blinkit,
  @HiveField(5)
  zepto,
  @HiveField(6)
  outsideBreakfast,
  @HiveField(7)
  lunch,
  @HiveField(8)
  restaurant,
  @HiveField(9)
  petrol,
  @HiveField(10)
  servicing,
  @HiveField(11)
  mobileRecharge,
  @HiveField(12)
  wifiRecharge,
  @HiveField(13)
  dmart,
  @HiveField(14)
  grocery,
  @HiveField(15)
  frullatto,
  @HiveField(16)
  friends,
  @HiveField(17)
  others,
}

final Map<Category, IconData> categoryIcons = {
  Category.bajajEmi: Icons.credit_card,
  Category.homeRent: Icons.house,
  Category.electricityBill: Icons.electrical_services,
  Category.zomat: Icons.fastfood,
  Category.blinkit: Icons.shopping_bag,
  Category.zepto: Icons.shopping_cart,
  Category.outsideBreakfast: Icons.breakfast_dining,
  Category.lunch: Icons.lunch_dining,
  Category.restaurant: Icons.restaurant,
  Category.petrol: Icons.local_gas_station,
  Category.servicing: Icons.build,
  Category.mobileRecharge: Icons.phone_android,
  Category.wifiRecharge: Icons.wifi,
  Category.dmart: Icons.store,
  Category.grocery: Icons.local_grocery_store,
  Category.frullatto: Icons.coffee,
  Category.friends: Icons.group,
  Category.others: Icons.category,
};

@HiveType(typeId: 1)
class Expense extends HiveObject {
  Expense({
    required this.amount,
    required this.date,
    required this.title,
    required this.category,
    this.paymentMethod, // New field for payment method
    this.friendNames,
    this.customCategory,
  }) : id = uuid.v4();

  @HiveField(0)
  final String id;

  @HiveField(1)
  final String title;

  @HiveField(2)
  final double amount;

  @HiveField(3)
  final DateTime date;

  @HiveField(4)
  final Category category;

  @HiveField(5)
  final String? paymentMethod;

  @HiveField(6)
  final List<String>? friendNames;

  @HiveField(7)
  final String? customCategory;

  String get formattedDate => formatter.format(date);
}


class ExpenseBucket {
  ExpenseBucket({required this.category, required this.expenses});
  ExpenseBucket.forCategory(List<Expense> allExpenses, this.category)
      : expenses =
  allExpenses.where((expense) => expense.category == category).toList();

  final Category category;
  final List<Expense> expenses;

  double get totalExpenses => expenses.fold(0, (sum, exp) => sum + exp.amount);
}
